name:                my-filter

dependencies:
- base >= 4.7 && < 5
- latex-formulae-image
- JuicyPixels
- bytestring
- filepath
- base64-bytestring

executables:
  my-filter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
