flags: {}
extra-package-dbs: []
packages:
- '.'
- ../langs/agda
- ../Development/Projects/agda-snippets/agda-snippets
- ../Development/Projects/agda-snippets/agda-snippets-hakyll
- ../Development/Projects/latex-formulae/latex-formulae-pandoc
- ../Development/Projects/latex-formulae/latex-formulae-image
- ../Development/Projects/latex-formulae/latex-formulae-hakyll
extra-deps:
- Agda-2.5.1
- EdisonAPI-1.3
- EdisonCore-1.3.1.1
- QuickCheck-2.8.2
- latex-formulae-hakyll-0.2.0.2
- monadplus-1.4.2
resolver: lts-5.8
